[build]
builder = "dockerfile"

[deploy]
startCommand = "node dist/server/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[env]
NODE_ENV = "production"
PORT = "8080"