import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: 'th' | 'en';
  setLanguage: (lang: 'th' | 'en') => void;
  toggleLanguage: () => void;
  isThai: boolean;
  t: (key: string, params?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<string, Record<string, string>> = {
  th: {
    // Navigation
    'nav.dashboard': 'แดชบอร์ด',
    'nav.contributions': 'ผลงาน',
    'nav.reports': 'รายงาน',
    'nav.userManagement': 'จัดการผู้ใช้',
    'nav.functionalTest': 'ทดสอบระบบ',
    'nav.logout': 'ออกจากระบบ',
    
    // Login
    'login.title': 'ยินดีต้อนรับ',
    'login.subtitle': 'เข้าสู่ระบบ ASC3 Contribution',
    'login.email': 'อีเมล',
    'login.password': 'รหัสผ่าน',
    'login.signIn': 'เข้าสู่ระบบ',
    'login.signingIn': 'กำลังเข้าสู่ระบบ...',
    'login.retrying': 'กำลังลองใหม่...',
    'login.noAccount': 'ยังไม่มีบัญชี?',
    'login.signUp': 'สมัครสมาชิกใหม่',
    'login.successTitle': 'เข้าสู่ระบบสำเร็จ! 🎉',
    'login.successMessage': 'กำลังนำคุณไปยังหน้าแดชบอร์ด...',
    'login.emailRequired': 'กรุณากรอกอีเมล',
    'login.passwordRequired': 'กรุณากรอกรหัสผ่าน',
    'login.invalidEmail': 'รูปแบบอีเมลไม่ถูกต้อง กรุณากรอกอีเมลในรูปแบบที่ถูกต้อง เช่น user@example.com',
    'login.loginError': 'เกิดข้อผิดพลาดในการเข้าสู่ระบบ',
    
    // Signup
    'signup.subtitle': 'ระบบจัดการผลงาน Presale',
    'signup.title': 'สมัครสมาชิกใหม่',
    'signup.description': 'กรอกข้อมูลเพื่อสร้างบัญชีใหม่',
    'signup.fullName': 'ชื่อ-นามสกุล',
    'signup.fullNamePlaceholder': 'กรอกชื่อ-นามสกุล',
    'signup.staffId': 'รหัสพนักงาน',
    'signup.staffIdPlaceholder': 'กรอกรหัสพนักงาน',
    'signup.email': 'อีเมล',
    'signup.emailPlaceholder': 'กรอกอีเมล',
    'signup.password': 'รหัสผ่าน',
    'signup.passwordPlaceholder': 'กรอกรหัสผ่าน',
    'signup.confirmPassword': 'ยืนยันรหัสผ่าน',
    'signup.confirmPasswordPlaceholder': 'ยืนยันรหัสผ่าน',
    'signup.accounts': 'ชื่อ Account ที่เกี่ยวข้อง',
    'signup.addAccount': 'เพิ่ม Account',
    'signup.accountPlaceholder': 'Account {number}',
    'signup.sales': 'ข้อมูล Sale ที่เกี่ยวข้อง',
    'signup.addSale': 'เพิ่ม Sale',
    'signup.saleNumber': 'Sale {number}',
    'signup.saleNamePlaceholder': 'ชื่อ-นามสกุล Sale',
    'signup.saleEmailPlaceholder': 'อีเมล Sale',
    'signup.signUp': 'สมัครสมาชิก',
    'signup.signingUp': 'กำลังสมัครสมาชิก...',
    'signup.haveAccount': 'มีบัญชีอยู่แล้ว?',
    'signup.login': 'เข้าสู่ระบบ',
    'signup.footerTitle': 'ASC3 Contribution Management System',
    'signup.footerCopyright': '© 2025 All rights reserved',
    'signup.fullNameRequired': 'กรุณากรอกชื่อ-นามสกุล',
    'signup.staffIdRequired': 'กรุณากรอกรหัสพนักงาน',
    'signup.emailRequired': 'กรุณากรอกอีเมล',
    'signup.passwordRequired': 'กรุณากรอกรหัสผ่าน',
    'signup.passwordMismatch': 'รหัสผ่านไม่ตรงกัน',
    'signup.invalidEmail': 'รูปแบบอีเมลไม่ถูกต้อง',
    'signup.success': 'สมัครสมาชิกสำเร็จ! กรุณารอการอนุมัติจาก Admin',
    'signup.error': 'เกิดข้อผิดพลาดในการสมัครสมาชิก',
    
    // Common
    'common.loading': 'กำลังโหลด...',
    'common.error': 'เกิดข้อผิดพลาด',
    'common.success': 'สำเร็จ',
    'common.cancel': 'ยกเลิก',
    'common.save': 'บันทึก',
    'common.edit': 'แก้ไข',
    'common.delete': 'ลบ',
    'common.add': 'เพิ่ม',
    'common.search': 'ค้นหา',
    'common.filter': 'กรอง',
    'common.sort': 'เรียงลำดับ',
    'common.refresh': 'รีเฟรช',
    'common.submit': 'ส่ง',
    'common.confirm': 'ยืนยัน',
    'common.yes': 'ใช่',
    'common.no': 'ไม่',
    'common.ok': 'ตกลง',
    'common.close': 'ปิด',
    'common.back': 'กลับ',
    'common.next': 'ถัดไป',
    'common.previous': 'ก่อนหน้า',
    'common.finish': 'เสร็จสิ้น',
    'common.start': 'เริ่มต้น',
    'common.stop': 'หยุด',
    'common.pause': 'หยุดชั่วคราว',
    'common.resume': 'ดำเนินต่อ',
    'common.retry': 'ลองใหม่',
    'common.tryAgain': 'ลองอีกครั้ง',
    'common.continue': 'ดำเนินต่อ',
    'common.complete': 'เสร็จสิ้น',
    'common.finalize': 'สรุป',
    'common.send': 'ส่ง',
    'common.receive': 'รับ',
    'common.upload': 'อัปโหลด',
    'common.download': 'ดาวน์โหลด',
    'common.import': 'นำเข้า',
    'common.export': 'ส่งออก',
    'common.backup': 'สำรองข้อมูล',
    'common.restore': 'กู้คืน',
    'common.sync': 'ซิงค์',
    'common.synchronize': 'ซิงโครไนซ์',
    'common.connect': 'เชื่อมต่อ',
    'common.disconnect': 'ตัดการเชื่อมต่อ',
    'common.link': 'ลิงก์',
    'common.attach': 'แนบ',
    'common.bind': 'ผูก',
    'common.associate': 'เชื่อมโยง',
    'common.relate': 'เกี่ยวข้อง',
    'common.correlate': 'สหสัมพันธ์',
    'common.merge': 'รวม',
    'common.combine': 'รวมกัน',
    'common.join': 'เข้าร่วม',
    'common.split': 'แยก',
    'common.separate': 'แยกออก',
    'common.divide': 'แบ่ง',
    'common.category': 'หมวดหมู่',
    'common.class': 'คลาส',
    'common.type': 'ประเภท',
    'common.kind': 'ชนิด',
    'common.order': 'ลำดับ',
    'common.arrangement': 'การจัดเรียง',
    'common.configuration': 'การกำหนดค่า',
    'common.setup': 'การตั้งค่า',
    'common.installation': 'การติดตั้ง',
    'common.deployment': 'การปรับใช้',
    'common.implementation': 'การดำเนินการ',
    'common.oldest': 'เก่าที่สุด',
    'common.earliest': 'เร็วที่สุด',
    'common.latest': 'ล่าสุด',
    'common.recent': 'ล่าสุด',
    'common.ancient': 'โบราณ',
    'common.modern': 'ทันสมัย',
    'common.chief': 'หัวหน้า',
    'common.leading': 'นำหน้า',
    'common.top': 'บนสุด',
    'common.highest': 'สูงสุด',
    'common.best': 'ดีที่สุด',
    'common.greatest': 'ยิ่งใหญ่ที่สุด',
    'common.good': 'ดี',
    'common.better': 'ดีกว่า',
    'common.excellent': 'ยอดเยี่ยม',
    'common.outstanding': 'โดดเด่น',
    'common.remarkable': 'น่าทึ่ง',
    'common.fair': 'ยุติธรรม',
    'common.just': 'ยุติธรรม',
    'common.right': 'ถูกต้อง',
    'common.correct': 'ถูกต้อง',
    'common.accurate': 'แม่นยำ',
    'common.precise': 'แม่นยำ',
    'common.exact': 'แน่นอน',
    'common.area': 'พื้นที่',
    'common.surface': 'พื้นผิว',
    'common.face': 'หน้า',
    'common.side': 'ด้าน',
    'common.edge': 'ขอบ',
    'common.corner': 'มุม',
    'common.angle': 'มุม',
    'common.direction': 'ทิศทาง',
    'common.point': 'จุด',
    'common.coordinate': 'พิกัด',
    'common.address': 'ที่อยู่',
    'common.route': 'เส้นทาง',
    'common.path': 'เส้นทาง',
    'common.way': 'ทาง',
    'common.activity': 'กิจกรรม',
    'common.action': 'การกระทำ',
    'common.operation': 'การดำเนินการ',
    'common.process': 'กระบวนการ',
    'common.procedure': 'ขั้นตอน',
    'common.step': 'ขั้นตอน',
    'common.stage': 'ระยะ',
    'common.phase': 'ระยะ',
    'common.level': 'ระดับ',
    'common.grade': 'เกรด',
    'common.rank': 'อันดับ',
    'common.status': 'สถานะ',
    'common.state': 'สถานะ',
    'common.condition': 'เงื่อนไข',
    'common.situation': 'สถานการณ์',
    'common.circumstance': 'สถานการณ์',
    'common.context': 'บริบท',
    'common.environment': 'สิ่งแวดล้อม',
    'common.surrounding': 'รอบข้าง',
    'common.atmosphere': 'บรรยากาศ',
    'common.climate': 'ภูมิอากาศ',
    'common.weather': 'สภาพอากาศ',
    'common.temperature': 'อุณหภูมิ',
    'common.humidity': 'ความชื้น',
    'common.pressure': 'ความดัน',
    'common.altitude': 'ระดับความสูง',
    'common.latitude': 'ละติจูด',
    'common.longitude': 'ลองจิจูด',
    
    // Theme
    'theme.light': 'โหมดสว่าง',
    'theme.dark': 'โหมดมืด',
    'theme.system': 'ตามระบบ',
    
    // Dashboard
    'dashboard.title': 'แดชบอร์ด',
    'dashboard.welcome': 'ยินดีต้อนรับ',
    'dashboard.overview': 'ภาพรวม',
    'dashboard.adminTitle': 'Admin Dashboard',
    'dashboard.adminWelcome': 'ยินดีต้อนรับกลับ! จัดการผลงานของทีมและภาพรวมระบบ',
    'dashboard.totalUsers': 'ผู้ใช้ทั้งหมด',
    'dashboard.totalAccounts': 'บัญชีทั้งหมด',
    'dashboard.totalContributions': 'ผลงานทั้งหมด',
    'dashboard.impactSummary': 'สรุปผลกระทบ',
    'dashboard.impactOverview': 'ภาพรวมผลกระทบ',
    'dashboard.userContributionsSummary': 'สรุปผลงานผู้ใช้',
    'dashboard.quickActions': 'การดำเนินการด่วน',
    'dashboard.manageUsers': 'จัดการผู้ใช้',
    'dashboard.viewReports': 'ดูรายงาน',
    'dashboard.reviewSubmissions': 'ตรวจสอบการส่ง',
    'dashboard.myAccountInfo': 'ข้อมูลบัญชีของฉัน',
    'dashboard.myContributions': 'ผลงานของฉัน',
    'dashboard.recentActivity': 'กิจกรรมล่าสุด',
    'dashboard.accountStatus': 'สถานะบัญชี',
    'dashboard.contributionsAll': 'ผลงานทั้งหมด',
    'dashboard.contributionsSubmitted': 'ผลงานที่ส่งแล้ว',
    'dashboard.contributionsDraft': 'ยัง Draft อยู่',
    'dashboard.impactStrategic': 'Strategic Impact',
    'dashboard.impactDepartment': 'Department Impact',
    'dashboard.impactTeam': 'Team-Level Impact',
    'dashboard.impactRoutine': 'Routine Contribution',
    'dashboard.contributionTimeline': 'Contribution Timeline',
    'dashboard.impactAcross': 'Impact Across',
    'dashboard.accounts': 'Accounts',
    'dashboard.statsContributionsAll': 'Contributions ทั้งหมด',
    'dashboard.statsContributionsSubmitted': 'Contributions ที่ส่งแล้ว',
    'dashboard.statsContributionsDraft': 'ยัง Draft อยู่',
    'dashboard.impactOverviewTitle': 'Impact Overview',
    'dashboard.trackTeamImpact': 'ติดตามผลกระทบของทีมตลอดทั้งปี',
    'dashboard.yearOverview': 'ภาพรวมปี',
    'dashboard.monthlyImpactMatrix': 'Monthly Impact Matrix',
    'dashboard.quickGlance': 'ดูแบบรวดเร็วตามผลกระทบ × เดือน',
    'dashboard.allUsers': 'ผู้ใช้ทั้งหมด',
    'dashboard.year': 'ปี',
    'dashboard.legendRoutine': 'Routine (Low Impact)',
    'dashboard.legendTeam': 'Team-Level (Medium Impact)',
    'dashboard.legendDepartment': 'Department (High Impact)',
    'dashboard.legendStrategic': 'Strategic (Critical Impact)',
    'dashboard.statistics': 'สถิติ',
    'dashboard.analytics': 'การวิเคราะห์',
    'dashboard.insights': 'ข้อมูลเชิงลึก',
    'dashboard.trends': 'แนวโน้ม',
    'dashboard.performance': 'ประสิทธิภาพ',
    'dashboard.metrics': 'ตัวชี้วัด',
    'dashboard.kpis': 'KPI',
    'dashboard.targets': 'เป้าหมาย',
    'dashboard.goals': 'เป้าหมาย',
    'dashboard.objectives': 'วัตถุประสงค์',
    'dashboard.milestones': 'จุดสำคัญ',
    'dashboard.deadlines': 'กำหนดส่ง',
    'dashboard.schedules': 'ตารางเวลา',
    'dashboard.timeline': 'ไทม์ไลน์',
    'dashboard.calendar': 'ปฏิทิน',
    'dashboard.events': 'เหตุการณ์',
    'dashboard.activities': 'กิจกรรม',
    'dashboard.tasks': 'งาน',
    'dashboard.assignments': 'การมอบหมาย',
    'dashboard.projects': 'โครงการ',
    'dashboard.initiatives': 'ความคิดริเริ่ม',
    'dashboard.campaigns': 'แคมเปญ',
    'dashboard.programs': 'โปรแกรม',
    'dashboard.systems': 'ระบบ',
    'dashboard.platforms': 'แพลตฟอร์ม',
    'dashboard.tools': 'เครื่องมือ',
    'dashboard.applications': 'แอปพลิเคชัน',
    'dashboard.services': 'บริการ',
    'dashboard.solutions': 'โซลูชัน',
    'dashboard.products': 'ผลิตภัณฑ์',
    'dashboard.features': 'ฟีเจอร์',
    'dashboard.capabilities': 'ความสามารถ',
    'dashboard.functions': 'ฟังก์ชัน',
    'dashboard.operations': 'การดำเนินงาน',
    'dashboard.processes': 'กระบวนการ',
    'dashboard.workflows': 'เวิร์กโฟลว์',
    'dashboard.procedures': 'ขั้นตอน',
    'dashboard.methods': 'วิธีการ',
    'dashboard.techniques': 'เทคนิค',
    'dashboard.approaches': 'แนวทาง',
    'dashboard.strategies': 'กลยุทธ์',
    'dashboard.tactics': 'ยุทธวิธี',
    'dashboard.plans': 'แผน',
    'dashboard.schemes': 'โครงการ',
    
    // Contributions
    'contributions.title': 'ผลงาน',
    'contributions.subtitle': 'จัดการผลงานของคุณสำหรับบัญชีในปี 2025',
    'contributions.createNew': 'สร้างผลงานใหม่',
    'contributions.total': 'รวมทั้งหมด',
    'contributions.approved': 'อนุมัติแล้ว',
    'contributions.pending': 'รออนุมัติ',
    'contributions.draft': 'ร่าง',
    'contributions.list': 'รายการผลงาน',
    'contributions.noContributions': 'ไม่มีผลงาน',
    'contributions.noContributionsDesc': 'เริ่มต้นสร้างผลงานแรกของคุณ',
    'contributions.account': 'บัญชี',
    'contributions.sale': 'Sale',
    'contributions.type': 'ประเภท',
    'contributions.month': 'เดือน',
    'contributions.description': 'คำอธิบาย',
    'contributions.status': 'สถานะ',
    'contributions.actions': 'การดำเนินการ',
    'contributions.view': 'ดู',
    'contributions.edit': 'แก้ไข',
    'contributions.delete': 'ลบ',
    'contributions.submit': 'ส่งอนุมัติ',
    'contributions.created': 'สร้างเมื่อ',
    'contributions.updated': 'อัปเดตเมื่อ',
    'contributions.tags': 'แท็ก',
    'contributions.impact': 'ผลกระทบ',
    'contributions.effort': 'ความพยายาม',
    'contributions.estimatedValue': 'มูลค่าประมาณการ',
    
    // Reports
    'reports.title': 'รายงาน',
    'reports.subtitle': 'ดูและวิเคราะห์ผลงานของทีม',
    'reports.comprehensiveReport': 'รายงานแบบครบถ้วน',
    'reports.printReport': 'พิมพ์รายงาน',
    'reports.filters': 'ตัวกรอง',
    'reports.allAccounts': 'บัญชีทั้งหมด',
    'reports.allSales': 'Sale ทั้งหมด',
    'reports.allPresales': 'Presale ทั้งหมด',
    'reports.allTypes': 'ประเภททั้งหมด',
    'reports.allImpacts': 'ผลกระทบทั้งหมด',
    'reports.allStatuses': 'สถานะทั้งหมด',
    'reports.applyFilters': 'ใช้ตัวกรอง',
    'reports.clearFilters': 'ล้างตัวกรอง',
    'reports.noData': 'ไม่มีข้อมูล',
    'reports.noDataDesc': 'ไม่พบข้อมูลตามเงื่อนไขที่เลือก',
    'reports.totalResults': 'ผลลัพธ์ทั้งหมด',
    'reports.showingResults': 'แสดงผลลัพธ์',
    'reports.of': 'จาก',
    'reports.results': 'ผลลัพธ์',
    
    // User Management
    'userManagement.title': 'จัดการผู้ใช้',
    'userManagement.subtitle': 'จัดการบัญชีผู้ใช้และสิทธิ์การเข้าถึง',
    'userManagement.createUser': 'สร้างผู้ใช้ใหม่',
    'userManagement.editUser': 'แก้ไขผู้ใช้',
    'userManagement.deleteUser': 'ลบผู้ใช้',
    'userManagement.viewProfile': 'ดูโปรไฟล์',
    'userManagement.allUsers': 'ผู้ใช้ทั้งหมด',
    'userManagement.admins': 'ผู้ดูแลระบบ',
    'userManagement.users': 'ผู้ใช้ทั่วไป',
    'userManagement.pending': 'รออนุมัติ',
    'userManagement.noUsers': 'ไม่มีผู้ใช้',
    'userManagement.noUsersDesc': 'ยังไม่มีผู้ใช้ในระบบ',
    'userManagement.loading': 'กำลังโหลดผู้ใช้...',
    'userManagement.userCreated': 'สร้างผู้ใช้สำเร็จ',
    'userManagement.userUpdated': 'อัปเดตผู้ใช้สำเร็จ',
    'userManagement.userDeleted': 'ลบผู้ใช้สำเร็จ',
    'userManagement.error': 'เกิดข้อผิดพลาด',
    'userManagement.confirmDelete': 'ยืนยันการลบ',
    'userManagement.confirmDeleteDesc': 'คุณแน่ใจหรือไม่ที่จะลบผู้ใช้นี้?',
    'userManagement.cancel': 'ยกเลิก',
    'userManagement.delete': 'ลบ',
    'userManagement.close': 'ปิด',
    'userManagement.save': 'บันทึก',
    'userManagement.edit': 'แก้ไข',
    'userManagement.view': 'ดู',
    'userManagement.role': 'บทบาท',
    'userManagement.status': 'สถานะ',
    'userManagement.createdAt': 'สร้างเมื่อ',
    'userManagement.updatedAt': 'อัปเดตเมื่อ',
    'userManagement.actions': 'การดำเนินการ',
    'userManagement.search': 'ค้นหา',
    'userManagement.searchPlaceholder': 'ค้นหาผู้ใช้...',
    'userManagement.filterBy': 'กรองตาม',
    'userManagement.showAll': 'แสดงทั้งหมด',
    'userManagement.showAdmins': 'แสดงผู้ดูแลระบบ',
    'userManagement.showUsers': 'แสดงผู้ใช้ทั่วไป',
    'userManagement.showPending': 'แสดงรออนุมัติ',
    
    // All Contributions
    'allContributions.title': 'ผลงานทั้งหมด',
    'allContributions.subtitle': 'ดูและจัดการผลงานของทุกคนในระบบ',
    'allContributions.noContributions': 'ไม่มีผลงาน',
    'allContributions.noContributionsDesc': 'ยังไม่มีผลงานในระบบ',
    'allContributions.loading': 'กำลังโหลดผลงาน...',
    'allContributions.filterBy': 'กรองตาม',
    'allContributions.allAccounts': 'บัญชีทั้งหมด',
    'allContributions.allUsers': 'ผู้ใช้ทั้งหมด',
    'allContributions.allTypes': 'ประเภททั้งหมด',
    'allContributions.allImpacts': 'ผลกระทบทั้งหมด',
    'allContributions.allStatuses': 'สถานะทั้งหมด',
    'allContributions.clearFilters': 'ล้างตัวกรอง',
    'allContributions.applyFilters': 'ใช้ตัวกรอง',
    'allContributions.search': 'ค้นหา',
    'allContributions.searchPlaceholder': 'ค้นหาผลงาน...',
    'allContributions.showingResults': 'แสดงผลลัพธ์',
    'allContributions.of': 'จาก',
    'allContributions.results': 'ผลลัพธ์',
    'allContributions.totalResults': 'ผลลัพธ์ทั้งหมด',
    'allContributions.actions': 'การดำเนินการ',
    'allContributions.view': 'ดู',
    'allContributions.edit': 'แก้ไข',
    'allContributions.delete': 'ลบ',
    'allContributions.submit': 'ส่ง',
    'allContributions.created': 'สร้างเมื่อ',
    'allContributions.updated': 'อัปเดตเมื่อ',
    'allContributions.account': 'บัญชี',
    'allContributions.sale': 'Sale',
    'allContributions.type': 'ประเภท',
    'allContributions.month': 'เดือน',
    'allContributions.description': 'คำอธิบาย',
    'allContributions.status': 'สถานะ',
    'allContributions.impact': 'ผลกระทบ',
    'allContributions.effort': 'ความพยายาม',
    'allContributions.estimatedValue': 'มูลค่าประมาณการ',
    'allContributions.tags': 'แท็ก',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.contributions': 'Contributions',
    'nav.reports': 'Reports',
    'nav.userManagement': 'User Management',
    'nav.functionalTest': 'Functional Test',
    'nav.logout': 'Logout',
    
    // Login
    'login.title': 'Welcome Back',
    'login.subtitle': 'Sign in to your ASC3 Contribution account',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.signIn': 'Sign in',
    'login.signingIn': 'Signing in...',
    'login.retrying': 'Retrying...',
    'login.noAccount': 'No account yet?',
    'login.signUp': 'Sign up for a new one',
    'login.successTitle': 'Login successful! 🎉',
    'login.successMessage': 'Redirecting you to the dashboard...',
    'login.emailRequired': 'Please enter your email',
    'login.passwordRequired': 'Please enter your password',
    'login.invalidEmail': 'Invalid email format. Please enter a valid email address like user@example.com',
    'login.loginError': 'An error occurred during login',
    
    // Signup
    'signup.subtitle': 'Presale Contribution Management System',
    'signup.title': 'Sign Up',
    'signup.description': 'Fill in the information to create a new account',
    'signup.fullName': 'Full Name',
    'signup.fullNamePlaceholder': 'Enter your full name',
    'signup.staffId': 'Staff ID',
    'signup.staffIdPlaceholder': 'Enter your staff ID',
    'signup.email': 'Email',
    'signup.emailPlaceholder': 'Enter your email',
    'signup.password': 'Password',
    'signup.passwordPlaceholder': 'Enter your password',
    'signup.confirmPassword': 'Confirm Password',
    'signup.confirmPasswordPlaceholder': 'Confirm your password',
    'signup.accounts': 'Related Account Names',
    'signup.addAccount': 'Add Account',
    'signup.accountPlaceholder': 'Account {number}',
    'signup.sales': 'Related Sale Information',
    'signup.addSale': 'Add Sale',
    'signup.saleNumber': 'Sale {number}',
    'signup.saleNamePlaceholder': 'Sale Full Name',
    'signup.saleEmailPlaceholder': 'Sale Email',
    'signup.signUp': 'Sign Up',
    'signup.signingUp': 'Signing up...',
    'signup.haveAccount': 'Already have an account?',
    'signup.login': 'Sign In',
    'signup.footerTitle': 'ASC3 Contribution Management System',
    'signup.footerCopyright': '© 2025 All rights reserved',
    'signup.fullNameRequired': 'Please enter your full name',
    'signup.staffIdRequired': 'Please enter your staff ID',
    'signup.emailRequired': 'Please enter your email',
    'signup.passwordRequired': 'Please enter your password',
    'signup.passwordMismatch': 'Passwords do not match',
    'signup.invalidEmail': 'Invalid email format',
    'signup.success': 'Sign up successful! Please wait for Admin approval',
    'signup.error': 'An error occurred during sign up',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.refresh': 'Refresh',
    'common.submit': 'Submit',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.finish': 'Finish',
    'common.start': 'Start',
    'common.stop': 'Stop',
    'common.pause': 'Pause',
    'common.resume': 'Resume',
    'common.retry': 'Retry',
    'common.tryAgain': 'Try Again',
    'common.continue': 'Continue',
    'common.complete': 'Complete',
    'common.finalize': 'Finalize',
    'common.send': 'Send',
    'common.receive': 'Receive',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.import': 'Import',
    'common.export': 'Export',
    'common.backup': 'Backup',
    'common.restore': 'Restore',
    'common.sync': 'Sync',
    'common.synchronize': 'Synchronize',
    'common.connect': 'Connect',
    'common.disconnect': 'Disconnect',
    'common.link': 'Link',
    'common.attach': 'Attach',
    'common.bind': 'Bind',
    'common.associate': 'Associate',
    'common.relate': 'Relate',
    'common.correlate': 'Correlate',
    'common.merge': 'Merge',
    'common.combine': 'Combine',
    'common.join': 'Join',
    'common.split': 'Split',
    'common.separate': 'Separate',
    'common.divide': 'Divide',
    'common.category': 'Category',
    'common.class': 'Class',
    'common.type': 'Type',
    'common.kind': 'Kind',
    'common.order': 'Order',
    'common.arrangement': 'Arrangement',
    'common.configuration': 'Configuration',
    'common.setup': 'Setup',
    'common.installation': 'Installation',
    'common.deployment': 'Deployment',
    'common.implementation': 'Implementation',
    'common.oldest': 'Oldest',
    'common.earliest': 'Earliest',
    'common.latest': 'Latest',
    'common.recent': 'Recent',
    'common.ancient': 'Ancient',
    'common.modern': 'Modern',
    'common.chief': 'Chief',
    'common.leading': 'Leading',
    'common.top': 'Top',
    'common.highest': 'Highest',
    'common.best': 'Best',
    'common.greatest': 'Greatest',
    'common.good': 'Good',
    'common.better': 'Better',
    'common.excellent': 'Excellent',
    'common.outstanding': 'Outstanding',
    'common.remarkable': 'Remarkable',
    'common.fair': 'Fair',
    'common.just': 'Just',
    'common.right': 'Right',
    'common.correct': 'Correct',
    'common.accurate': 'Accurate',
    'common.precise': 'Precise',
    'common.exact': 'Exact',
    'common.area': 'Area',
    'common.surface': 'Surface',
    'common.face': 'Face',
    'common.side': 'Side',
    'common.edge': 'Edge',
    'common.corner': 'Corner',
    'common.angle': 'Angle',
    'common.direction': 'Direction',
    'common.point': 'Point',
    'common.coordinate': 'Coordinate',
    'common.address': 'Address',
    'common.route': 'Route',
    'common.path': 'Path',
    'common.way': 'Way',
    'common.activity': 'Activity',
    'common.action': 'Action',
    'common.operation': 'Operation',
    'common.process': 'Process',
    'common.procedure': 'Procedure',
    'common.step': 'Step',
    'common.stage': 'Stage',
    'common.phase': 'Phase',
    'common.level': 'Level',
    'common.grade': 'Grade',
    'common.rank': 'Rank',
    'common.status': 'Status',
    'common.state': 'State',
    'common.condition': 'Condition',
    'common.situation': 'Situation',
    'common.circumstance': 'Circumstance',
    'common.context': 'Context',
    'common.environment': 'Environment',
    'common.surrounding': 'Surrounding',
    'common.atmosphere': 'Atmosphere',
    'common.climate': 'Climate',
    'common.weather': 'Weather',
    'common.temperature': 'Temperature',
    'common.humidity': 'Humidity',
    'common.pressure': 'Pressure',
    'common.altitude': 'Altitude',
    'common.latitude': 'Latitude',
    'common.longitude': 'Longitude',
    
    // Theme
    'theme.light': 'Light Mode',
    'theme.dark': 'Dark Mode',
    'theme.system': 'System',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome',
    'dashboard.overview': 'Overview',
    'dashboard.adminTitle': 'Admin Dashboard',
    'dashboard.adminWelcome': 'Welcome back! Manage your team\'s contributions and system overview.',
    'dashboard.totalUsers': 'Total Users',
    'dashboard.totalAccounts': 'Total Accounts',
    'dashboard.totalContributions': 'Total Contributions',
    'dashboard.impactSummary': 'Impact Summary',
    'dashboard.impactOverview': 'Impact Overview',
    'dashboard.userContributionsSummary': 'User Contributions Summary',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.manageUsers': 'Manage Users',
    'dashboard.viewReports': 'View Reports',
    'dashboard.reviewSubmissions': 'Review Submissions',
    'dashboard.myAccountInfo': 'My Account Information',
    'dashboard.myContributions': 'My Contributions',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.accountStatus': 'Account Status',
    'dashboard.contributionsAll': 'Contributions ทั้งหมด',
    'dashboard.contributionsSubmitted': 'Contributions ที่ส่งแล้ว',
    'dashboard.contributionsDraft': 'ยัง Draft อยู่',
    'dashboard.impactStrategic': 'Strategic Impact',
    'dashboard.impactDepartment': 'Department Impact',
    'dashboard.impactTeam': 'Team-Level Impact',
    'dashboard.impactRoutine': 'Routine Contribution',
    'dashboard.contributionTimeline': 'Contribution Timeline',
    'dashboard.impactAcross': 'Impact Across',
    'dashboard.accounts': 'Accounts',
    'dashboard.statsContributionsAll': 'Contributions ทั้งหมด',
    'dashboard.statsContributionsSubmitted': 'Contributions ที่ส่งแล้ว',
    'dashboard.statsContributionsDraft': 'ยัง Draft อยู่',
    'dashboard.impactOverviewTitle': 'Impact Overview',
    'dashboard.trackTeamImpact': 'Track your team\'s impact throughout',
    'dashboard.yearOverview': 'Year Overview',
    'dashboard.monthlyImpactMatrix': 'Monthly Impact Matrix',
    'dashboard.quickGlance': 'Quick glance by impact × month',
    'dashboard.allUsers': 'All users',
    'dashboard.year': 'Year',
    'dashboard.legendRoutine': 'Routine (Low Impact)',
    'dashboard.legendTeam': 'Team-Level (Medium Impact)',
    'dashboard.legendDepartment': 'Department (High Impact)',
    'dashboard.legendStrategic': 'Strategic (Critical Impact)',
    'dashboard.statistics': 'Statistics',
    'dashboard.analytics': 'Analytics',
    'dashboard.insights': 'Insights',
    'dashboard.trends': 'Trends',
    'dashboard.performance': 'Performance',
    'dashboard.metrics': 'Metrics',
    'dashboard.kpis': 'KPIs',
    'dashboard.targets': 'Targets',
    'dashboard.goals': 'Goals',
    'dashboard.objectives': 'Objectives',
    'dashboard.milestones': 'Milestones',
    'dashboard.deadlines': 'Deadlines',
    'dashboard.schedules': 'Schedules',
    'dashboard.timeline': 'Timeline',
    'dashboard.calendar': 'Calendar',
    'dashboard.events': 'Events',
    'dashboard.activities': 'Activities',
    'dashboard.tasks': 'Tasks',
    'dashboard.assignments': 'Assignments',
    'dashboard.projects': 'Projects',
    'dashboard.initiatives': 'Initiatives',
    'dashboard.campaigns': 'Campaigns',
    'dashboard.programs': 'Programs',
    'dashboard.systems': 'Systems',
    'dashboard.platforms': 'Platforms',
    'dashboard.tools': 'Tools',
    'dashboard.applications': 'Applications',
    'dashboard.services': 'Services',
    'dashboard.solutions': 'Solutions',
    'dashboard.products': 'Products',
    'dashboard.features': 'Features',
    'dashboard.capabilities': 'Capabilities',
    'dashboard.functions': 'Functions',
    'dashboard.operations': 'Operations',
    'dashboard.processes': 'Processes',
    'dashboard.workflows': 'Workflows',
    'dashboard.procedures': 'Procedures',
    'dashboard.methods': 'Methods',
    'dashboard.techniques': 'Techniques',
    'dashboard.approaches': 'Approaches',
    'dashboard.strategies': 'Strategies',
    'dashboard.tactics': 'Tactics',
    'dashboard.plans': 'Plans',
    'dashboard.schemes': 'Schemes',
    
    // Contributions
    'contributions.title': 'Contributions',
    'contributions.subtitle': 'Manage your contributions for accounts in 2025',
    'contributions.createNew': 'Create New Contribution',
    'contributions.total': 'Total',
    'contributions.approved': 'Approved',
    'contributions.pending': 'Pending',
    'contributions.draft': 'Draft',
    'contributions.list': 'Contributions List',
    'contributions.noContributions': 'No Contributions',
    'contributions.noContributionsDesc': 'Start by creating your first contribution',
    'contributions.account': 'Account',
    'contributions.sale': 'Sale',
    'contributions.type': 'Type',
    'contributions.month': 'Month',
    'contributions.description': 'Description',
    'contributions.status': 'Status',
    'contributions.actions': 'Actions',
    'contributions.view': 'View',
    'contributions.edit': 'Edit',
    'contributions.delete': 'Delete',
    'contributions.submit': 'Submit for Approval',
    'contributions.created': 'Created',
    'contributions.updated': 'Updated',
    'contributions.tags': 'Tags',
    'contributions.impact': 'Impact',
    'contributions.effort': 'Effort',
    'contributions.estimatedValue': 'Estimated Value',
    
    // Reports
    'reports.title': 'Reports',
    'reports.subtitle': 'View and analyze team contributions',
    'reports.comprehensiveReport': 'Comprehensive Report',
    'reports.printReport': 'Print Report',
    'reports.filters': 'Filters',
    'reports.allAccounts': 'All Accounts',
    'reports.allSales': 'All Sales',
    'reports.allPresales': 'All Presales',
    'reports.allTypes': 'All Types',
    'reports.allImpacts': 'All Impacts',
    'reports.allStatuses': 'All Statuses',
    'reports.applyFilters': 'Apply Filters',
    'reports.clearFilters': 'Clear Filters',
    'reports.noData': 'No Data',
    'reports.noDataDesc': 'No data found matching the selected criteria',
    'reports.totalResults': 'Total Results',
    'reports.showingResults': 'Showing',
    'reports.of': 'of',
    'reports.results': 'results',
    
    // User Management
    'userManagement.title': 'User Management',
    'userManagement.subtitle': 'Manage user accounts and access permissions',
    'userManagement.createUser': 'Create New User',
    'userManagement.editUser': 'Edit User',
    'userManagement.deleteUser': 'Delete User',
    'userManagement.viewProfile': 'View Profile',
    'userManagement.allUsers': 'All Users',
    'userManagement.admins': 'Administrators',
    'userManagement.users': 'Regular Users',
    'userManagement.pending': 'Pending Approval',
    'userManagement.noUsers': 'No Users',
    'userManagement.noUsersDesc': 'No users in the system yet',
    'userManagement.loading': 'Loading users...',
    'userManagement.userCreated': 'User created successfully',
    'userManagement.userUpdated': 'User updated successfully',
    'userManagement.userDeleted': 'User deleted successfully',
    'userManagement.error': 'An error occurred',
    'userManagement.confirmDelete': 'Confirm Delete',
    'userManagement.confirmDeleteDesc': 'Are you sure you want to delete this user?',
    'userManagement.cancel': 'Cancel',
    'userManagement.delete': 'Delete',
    'userManagement.close': 'Close',
    'userManagement.save': 'Save',
    'userManagement.edit': 'Edit',
    'userManagement.view': 'View',
    'userManagement.role': 'Role',
    'userManagement.status': 'Status',
    'userManagement.createdAt': 'Created At',
    'userManagement.updatedAt': 'Updated At',
    'userManagement.actions': 'Actions',
    'userManagement.search': 'Search',
    'userManagement.searchPlaceholder': 'Search users...',
    'userManagement.filterBy': 'Filter by',
    'userManagement.showAll': 'Show All',
    'userManagement.showAdmins': 'Show Administrators',
    'userManagement.showUsers': 'Show Regular Users',
    'userManagement.showPending': 'Show Pending',
    
    // All Contributions
    'allContributions.title': 'All Contributions',
    'allContributions.subtitle': 'View and manage contributions from everyone in the system',
    'allContributions.noContributions': 'No Contributions',
    'allContributions.noContributionsDesc': 'No contributions in the system yet',
    'allContributions.loading': 'Loading contributions...',
    'allContributions.filterBy': 'Filter by',
    'allContributions.allAccounts': 'All Accounts',
    'allContributions.allUsers': 'All Users',
    'allContributions.allTypes': 'All Types',
    'allContributions.allImpacts': 'All Impacts',
    'allContributions.allStatuses': 'All Statuses',
    'allContributions.clearFilters': 'Clear Filters',
    'allContributions.applyFilters': 'Apply Filters',
    'allContributions.search': 'Search',
    'allContributions.searchPlaceholder': 'Search contributions...',
    'allContributions.showingResults': 'Showing',
    'allContributions.of': 'of',
    'allContributions.results': 'results',
    'allContributions.totalResults': 'Total Results',
    'allContributions.actions': 'Actions',
    'allContributions.view': 'View',
    'allContributions.edit': 'Edit',
    'allContributions.delete': 'Delete',
    'allContributions.submit': 'Submit',
    'allContributions.created': 'Created',
    'allContributions.updated': 'Updated',
    'allContributions.account': 'Account',
    'allContributions.sale': 'Sale',
    'allContributions.type': 'Type',
    'allContributions.month': 'Month',
    'allContributions.description': 'Description',
    'allContributions.status': 'Status',
    'allContributions.impact': 'Impact',
    'allContributions.effort': 'Effort',
    'allContributions.estimatedValue': 'Estimated Value',
    'allContributions.tags': 'Tags',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  // Initialize language from localStorage or default to 'th'
  const [language, setLanguage] = useState<'th' | 'en'>(() => {
    const savedLanguage = localStorage.getItem('language') as 'th' | 'en';
    return savedLanguage || 'th';
  });

  const toggleLanguage = () => {
    const newLanguage = language === 'th' ? 'en' : 'th';
    setLanguage(newLanguage);
    localStorage.setItem('language', newLanguage);
    console.log('🔍 Language toggled to:', newLanguage);
  };

  const isThai = language === 'th';

  const t = (key: string, params?: Record<string, any>): string => {
    let translation = translations[language][key] || key;
    
    // Replace parameters in translation
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{${param}}`, params[param]);
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, isThai, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
